version: "3.7"
services:
  # cwagent:
  #   image: amazon/cloudwatch-agent:latest
  #   volumes:
  #     - ./amazon-cloudwatch-agent.json:/opt/aws/amazon-cloudwatch-agent/bin/default_linux_config.json # agent config
  #     - ~/.aws:/root/.aws # required for authentication
  #   environment:
  #     - AWS_REGION=ca-central-1
  #     - AWS_PROFILE=default
  #   ports:
  #     - "4316:4316"
  #     - "4317:4317"
  #     - "2000:2000"

  otel:
    ports:
      - 4317:4317
      - 55680:55680
      - 8889:8888
    environment:
      - AWS_REGION=ca-central-1
    volumes:
      - "./otel-config.yaml:/otel-local-config.yaml"
    container_name: awscollector
    image: public.ecr.aws/aws-observability/aws-otel-collector:latest
    command: --config otel-local-config.yaml

  app:
    build:
      context: .
    environment:
      - AWS_REGION=ca-central-1
      - AWS_PROFILE=default
      - INSTANCE_ID
      - LISTEN_ADDRESS=0.0.0.0:8080
      - OTEL_RESOURCE_ATTRIBUTES=service.name=aws-otel-integ-test
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel:4317
      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://otel:4317/v1/traces
      - OTEL_AWS_APPLICATION_SIGNALS_EXPORTER_ENDPOINT=http://otel:4317/v1/metrics
      - ASPNETCORE_URLS=http://+:8080
      - OTEL_AWS_APPLICATION_SIGNALS_ENABLED=true
      - OTEL_TRACES_SAMPLER=xray
      - OTEL_TRACES_SAMPLER_ARG=endpoint=http://otel:2000,polling_interval=1
      - OTEL_DOTNET_AUTO_PLUGINS="AWS.Distro.OpenTelemetry.AutoInstrumentation.Plugin, AWS.Distro.OpenTelemetry.AutoInstrumentation"
      - OTEL_EXPORTER_OTLP_PROTOCOL="protobuf"
    ports:
      - "8080:8080"
